sudo: required
services:
  - docker
before_install:
  - docker build -t gonenshafry/docker-react -f Dockerfile.dev .
script:
  - docker run gonenshafry/docker-react npm run test -- --converage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "Dockerreact-env"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-550012192858"
  bucket-path: "Dockerreact-env"
on:
  branch: master