sudo: required
services:
  - docker
environment:
  - WATCHPACK_POLLING=true
before_install:
  - docker build -t gonenshafry/docker-react -f Dockerfile.dev .
script:
  - docker run gonenshafry/docker-react npm run test -- --converage